# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x1a\x0cnanopb.proto\"\xfa\x01\n\x0cToSbcMessage\x12$\n\x0c\x62\x61ttery_info\x18\x01 \x01(\x0b\x32\x0c.BatteryInfoH\x00\x12%\n\rpower_off_req\x18\x02 \x01(\x0b\x32\x0c.PowerOffReqH\x00\x12\'\n\x0e\x64omain_id_info\x18\x03 \x01(\x0b\x32\r.DomainIdInfoH\x00\x12!\n\x0bhw_info_res\x18\x04 \x01(\x0b\x32\n.HwInfoResH\x00\x12+\n\x10network_info_req\x18\x05 \x01(\x0b\x32\x0f.NetworkInfoReqH\x00\x12\x1c\n\x08ping_req\x18\x06 \x01(\x0b\x32\x08.PingReqH\x00\x42\x06\n\x04\x64\x61ta\"2\n\x0b\x42\x61tteryInfo\x12\x0f\n\x07voltage\x18\x01 \x01(\x02\x12\x12\n\npercentage\x18\x02 \x01(\x02\"#\n\x0bPowerOffReq\x12\x14\n\x0cis_low_power\x18\x01 \x01(\x08\"\x1a\n\x0c\x44omainIdInfo\x12\n\n\x02id\x18\x01 \x01(\r\"D\n\tHwInfoRes\x12\x17\n\x0f\x62uild_timestamp\x18\x01 \x01(\x04\x12\x1e\n\x0fgit_commit_hash\x18\x02 \x01(\tB\x05\x92?\x02p\x07\"\x10\n\x0eNetworkInfoReq\"\t\n\x07PingReq\"\xc7\x01\n\x0cToMcuMessage\x12\x1a\n\x07ip_info\x18\x01 \x01(\x0b\x32\x07.IpInfoH\x00\x12!\n\x0bhw_info_req\x18\x02 \x01(\x0b\x32\n.HwInfoReqH\x00\x12%\n\rpower_off_evt\x18\x03 \x01(\x0b\x32\x0c.PowerOffEvtH\x00\x12+\n\x10network_info_res\x18\x04 \x01(\x0b\x32\x0f.NetworkInfoResH\x00\x12\x1c\n\x08ping_res\x18\x05 \x01(\x0b\x32\x08.PingResH\x00\x42\x06\n\x04\x64\x61ta\"\x1d\n\x06IpInfo\x12\x13\n\x04ipv4\x18\x01 \x01(\x0c\x42\x05\x92?\x02\x08\x04\"\x0b\n\tHwInfoReq\"\r\n\x0bPowerOffEvt\"b\n\x0eNetworkInfoRes\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.NetworkType\x12\x13\n\x04ssid\x18\x02 \x01(\tB\x05\x92?\x02p \x12\x0c\n\x04rssi\x18\x03 \x01(\x11\x12\x11\n\tfrequency\x18\x04 \x01(\r\"\x1a\n\x07PingRes\x12\x0f\n\x07ping_ms\x18\x01 \x01(\x02*Q\n\x0bNetworkType\x12\x15\n\x11NETWORK_TYPE_NONE\x10\x00\x12\x15\n\x11NETWORK_TYPE_WLAN\x10\x01\x12\x14\n\x10NETWORK_TYPE_LAN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HWINFORES'].fields_by_name['git_commit_hash']._loaded_options = None
  _globals['_HWINFORES'].fields_by_name['git_commit_hash']._serialized_options = b'\222?\002p\007'
  _globals['_IPINFO'].fields_by_name['ipv4']._loaded_options = None
  _globals['_IPINFO'].fields_by_name['ipv4']._serialized_options = b'\222?\002\010\004'
  _globals['_NETWORKINFORES'].fields_by_name['ssid']._loaded_options = None
  _globals['_NETWORKINFORES'].fields_by_name['ssid']._serialized_options = b'\222?\002p '
  _globals['_NETWORKTYPE']._serialized_start=890
  _globals['_NETWORKTYPE']._serialized_end=971
  _globals['_TOSBCMESSAGE']._serialized_start=33
  _globals['_TOSBCMESSAGE']._serialized_end=283
  _globals['_BATTERYINFO']._serialized_start=285
  _globals['_BATTERYINFO']._serialized_end=335
  _globals['_POWEROFFREQ']._serialized_start=337
  _globals['_POWEROFFREQ']._serialized_end=372
  _globals['_DOMAINIDINFO']._serialized_start=374
  _globals['_DOMAINIDINFO']._serialized_end=400
  _globals['_HWINFORES']._serialized_start=402
  _globals['_HWINFORES']._serialized_end=470
  _globals['_NETWORKINFOREQ']._serialized_start=472
  _globals['_NETWORKINFOREQ']._serialized_end=488
  _globals['_PINGREQ']._serialized_start=490
  _globals['_PINGREQ']._serialized_end=499
  _globals['_TOMCUMESSAGE']._serialized_start=502
  _globals['_TOMCUMESSAGE']._serialized_end=701
  _globals['_IPINFO']._serialized_start=703
  _globals['_IPINFO']._serialized_end=732
  _globals['_HWINFOREQ']._serialized_start=734
  _globals['_HWINFOREQ']._serialized_end=745
  _globals['_POWEROFFEVT']._serialized_start=747
  _globals['_POWEROFFEVT']._serialized_end=760
  _globals['_NETWORKINFORES']._serialized_start=762
  _globals['_NETWORKINFORES']._serialized_end=860
  _globals['_PINGRES']._serialized_start=862
  _globals['_PINGRES']._serialized_end=888
# @@protoc_insertion_point(module_scope)
